services: 
  imagenfront:
    image: alepellereca/imagenfront
    restart: always
    ports:
      - "3000:3000"  
    volumes: 
    - .:/opt

  imagenback:
    image: alepellereca/imagenback
    restart: always
    ports:
    - "8081:8081"  
    volumes: 
    - .:/opt

